version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pokedex
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_pokedex
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql_data:
